## Chapter1 : Getting and Knowing your Data

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [2]:
import pandas as pd
order_details = pd.read_csv(
    filepath_or_buffer=r"/home/chris/Documents/Jupyter Notebook/Demo1/Doc/data.tsv.txt",
    sep="\t"
)

order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [5]:
pd.read_table(filepath_or_buffer=r"/home/chris/Documents/Jupyter Notebook/Demo1/Doc/insurance.csv", sep=",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 1. perform initial Analysis

In [7]:
# function - ()
# Attribute

order_details.shape  # shape is attribute

(4622, 5)

In [ ]:
### Terminology alert

1. rows - observations / records
2. coloumn - features / parameters

In [8]:
order_details.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [9]:
order_details.isnull().sum() ## Chain of function or chain of commands

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [10]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [12]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [11]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

## 2.Find out the items sold in hotel

In [14]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [16]:
order_details["item_name"].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [6]:
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## 1.3 Give me the list of Top 5 Selling Items

In [7]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values() #Chain method

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [11]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False) #Chain method

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [12]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False).head() #Chain method

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [13]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False).head(10) #Chain method

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

In [14]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head(10) #Chain method

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Veggie Salad                         6
Name: quantity, dtype: int64

## Chapter 2 : Data Cleaning

In [3]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [4]:
order_details["item_price"]

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

In [6]:
order_details["item_price"].str.replace("$", "")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [7]:
order_details["item_price"].str.replace("$", "").astype(float) #object to float

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [8]:
order_details #still item price is $ symbol is there need to update

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
order_details["item_price"] = order_details["item_price"].str.replace("$", "").astype(float) #updated

In [10]:
9order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [11]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [ ]:
## Task
1. Find out top 5 Selling item individual revenue it made
2. total revenue of the top 5 items sold
3. find atlease two more question on the same data set

## Chapter 3 - Pandas Data Structure

 1. 1D - Series
 2. 2D - DataFrame

In [16]:
pd.Series(data=(1,2,4,5,"$5.4"))

0       1
1       2
2       4
3       5
4    $5.4
dtype: object

In [17]:
pd.Series(data=[1,2,4,5,"$5.4"])

0       1
1       2
2       4
3       5
4    $5.4
dtype: object

In [21]:
pd.DataFrame(data = {"Name: ":["Chris","Loie","Jooh","Mic"],
                    "Math: " : [50,20,40,30],
                     "Science: " : [98,94,23,42],
                    })

  Name:   Math:         Science:
0  Chris            50         98
1   Loie            20         94
2   Jooh            40         23
3    Mic            30         42

## Task
 1.Create Meaningfull Series
 2.Create Meaningfull Dataset using Pandas DataFrame with Dict 5 Observation across 6 Features

## Chapter 4 - Filtering and selection and sorting

In [23]:
euro_data = pd.read_csv("/home/chris/Documents/Jupyter Notebook/Demo1/Doc/Euro_2012_stats_TEAM.csv")
euro_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [27]:
Filtered_euro_data = euro_data [["% Goals-to-shots","Team","Goals","Players Used"]]
Filtered_euro_data

   % Goals-to-shots                 Team  Goals  Players Used
0             16.0%              Croatia      4            16
1             12.9%       Czech Republic      4            19
2             20.0%              Denmark      4            15
3             17.2%              England      5            16
4              6.5%               France      3            19
5             15.6%              Germany     10            17
6             19.2%               Greece      5            20
7              7.5%                Italy      6            19
8              4.1%          Netherlands      2            15
9              5.2%               Poland      2            17
10             9.3%             Portugal      6            16
11             5.2%  Republic of Ireland      1            17
12            12.5%               Russia      5            16
13            16.0%                Spain     12            18
14            13.8%               Sweden      5            18
15             6.0%              Ukraine      2            18